In [1]:
import pandas as pd
df=pd.read_csv('sai2026.csv')
df.head()

,Batsman,opponent,Venue,innings,Pitch_type,Runs,Ball_played,Strikerate,4s,6s,Dismissed,Length,Bowl_speed,Bowling_type,Match_over,Bowler_over
0,Sai,PBKS,New Chandigarh,1st,Flat,13,11,118,2,0,Catch,Fuller,131,Left arm fast medium,4th,1
1,Sai,RR,Ahmedabad,2nd,bouncy,73,44,165,9,3,Catch,length,93,Right arm leg break,11th,1
2,Sai,DC,Delhi,1st,Flat,12,7,171,2,0,Bowled,length,137,Right arm medium fast,3rd,1
3,Sai,LSG,Lucknow,2nd,Spin,15,14,107,3,0,Catch,length,96,Right arm leg break,6th,1
4,Sai,KKR,Ahmedabad,2nd,bouncy,22,16,137,1,2,Catch,length,90,Right arm off spin,6th,1

In [2]:
df.info()
df.discribe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Batsman       17 non-null     object
 1   opponent      17 non-null     object
 2   Venue         17 non-null     object
 3   innings       17 non-null     object
 4   Pitch_type    17 non-null     object
 5   Runs          17 non-null     int64
 6   Ball_played   17 non-null     int64
 7   Strikerate    17 non-null     int64
 8   4s            17 non-null     int64
 9   6s            17 non-null     int64
 10  Dismissed     17 non-null     object
 11  Length        17 non-null     object
 12  Bowl_speed    17 non-null     object
 13  Bowling_type  17 non-null     object
 14  Match_over    17 non-null     object
 15  Bowler_over   17 non-null     object
dtypes: int64(5), object(11)
memory usage: 2.3+ KB

AttributeError: 'DataFrame' object has no attribute 'discribe'

In [ ]:
df.isnull().sum()

In [3]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['batsman', 'opponent', 'venue', 'innings', 'pitch_type', 'runs',
       'ball_played', 'strikerate', '4s', '6s', 'dismissed', 'length',
       'bowl_speed', 'bowling_type', 'match_over', 'bowler_over'],
      dtype='object')

In [4]:
df.describe()
df.describe(include='object')

,batsman,opponent,venue,innings,pitch_type,dismissed,length,bowl_speed,bowling_type,match_over,bowler_over
count,17,17,17,17,17,17,17,17,17,17,17
unique,1,9,9,2,4,4,5,14,9,11,5
top,Sai,RCB,Ahmedabad,2nd,Flat,Catch,length,136,Right arm medium fast,3rd,1
freq,17,4,8,10,7,13,7,3,4,3,6

In [5]:
df.nunique()

batsman          1
opponent         9
venue            9
innings          2
pitch_type       4
runs            16
ball_played     16
strikerate      15
4s              11
6s               6
dismissed        4
length           5
bowl_speed      14
bowling_type     9
match_over      11
bowler_over      5
dtype: int64

In [6]:
for col in df.columns:
    print(col)
    print(df[col].unique())

batsman
['Sai']
opponent
['PBKS' 'RR' 'DC' 'LSG' 'KKR' 'MI' 'RCB' 'CSK' 'SRH']
venue
['New Chandigarh' 'Ahmedabad' 'Delhi' 'Lucknow' 'Bengaluru' 'Chennai'
 'Jaipur' 'Kolkata' 'Dharamsala']
innings
['1st' '2nd']
pitch_type
['Flat' 'bouncy' 'Spin' 'Balanced']
runs
[ 13  73  12  15  22   0 100  87   6  57  55  61  53  84  14  58]
ball_played
[11 44  7 14 16  1 58 46  5 41 36 28 53  9 32 12]
strikerate
[118 165 171 107 137   0 173 190 120 139 153 159 155 181 100]
4s
[ 2  9  3  1  0 11  4  5  6  7  8]
6s
[0 3 2 5 7 1]
dismissed
['Catch' 'Bowled' 'Not out' 'Hit wicket']
length
['Fuller' 'length' 'Short' 'Full toss' 'nill']
bowl_speed
['131' '93' '137' '96' '90' '136' '143' '87' '134' '94' 'nill' '133' '135'
 '138']
bowling_type
['Left arm fast medium' 'Right arm leg break' 'Right arm medium fast'
 'Right arm off spin' 'Right arm fast' 'left arm off spin'
 'Right arm fast medium' 'Right arm leg spin' 'nill']
match_over
['4th ' '11th' '3rd' '6th' '1st' '16th' '17th' '15th' 'nill' '19th' '13th']
bowler_over
['1' '3' '4' '2' 'nill']

In [7]:
df["runs"].value_counts()
df["pitch_type"].value_counts()
df["opponent"].value_counts()

opponent
RCB     4
RR      3
PBKS    2
KKR     2
CSK     2
DC      1
LSG     1
MI      1
SRH     1
Name: count, dtype: int64

In [8]:
df["Boundary Runs"] = df["4s"]*4 + df["6s"]*6

In [9]:
df["Singles"] = df["runs"] - df["Boundary Runs"]

In [10]:
df["Boundary %"] = (df["Boundary Runs"]/df["runs"])*100

In [11]:
df["Boundary %"] = (df["Boundary Runs"]/df["runs"].replace(0,1))*100

In [12]:
df["Fifty"] = df["runs"]>=50

In [13]:
df["Century"] = df["runs"]>=100

In [14]:
df["runs"].mean()

np.float64(42.470588235294116)

In [15]:
df["runs"].max()

100

In [16]:
df["strikerate"].mean()

np.float64(141.0)

In [17]:
df.groupby("opponent")["runs"].sum()

opponent
CSK     171
DC       12
KKR      75
LSG      15
MI        0
PBKS     70
RCB     132
RR      186
SRH      61
Name: runs, dtype: int64

In [18]:
df.groupby("pitch_type")["runs"].mean()

pitch_type
Balanced    55.000000
Flat        47.714286
Spin        51.000000
bouncy      33.000000
Name: runs, dtype: float64

In [19]:
df.groupby("venue")["runs"].sum()

venue
Ahmedabad         315
Bengaluru         100
Chennai            87
Delhi              12
Dharamsala         14
Jaipur             55
Kolkata            53
Lucknow            15
New Chandigarh     71
Name: runs, dtype: int64

In [20]:
df.groupby("innings")["runs"].sum().reset_index(name="total_runs")

  innings  total_runs
0     1st         337
1     2nd         385

In [21]:
df.groupby("bowling_type")["runs"].mean()

bowling_type
Left arm fast medium     13.0
Right arm fast           50.0
Right arm fast medium    47.5
Right arm leg break      44.0
Right arm leg spin       55.0
Right arm medium fast    28.5
Right arm off spin       22.0
left arm off spin        87.0
nill                     53.0
Name: runs, dtype: float64

In [22]:
df["dismissed"].unique()

array(['Catch', 'Bowled', 'Not out', 'Hit wicket'], dtype=object)

In [23]:
out_df = df[df["dismissed"] != "not_out"]

In [24]:
df["dismissed"].value_counts()

dismissed
Catch         13
Hit wicket     2
Bowled         1
Not out        1
Name: count, dtype: int64

In [25]:
out_df = df[df["dismissed"] == "Yes"]

In [26]:
df["length"].unique()

array(['Fuller', 'length', 'Short', 'Full toss', 'nill'], dtype=object)

In [27]:
df["length"].value_counts(dropna=False)

length
length       7
Fuller       4
Short        3
Full toss    2
nill         1
Name: count, dtype: int64

In [28]:
out_df = df[df["dismissed"] != "nill"]

In [29]:
print(out_df.groupby(["length", "dismissed"]).size().reset_index(name="dismissal"))

      length   dismissed  dismissal
0  Full toss       Catch          1
1  Full toss  Hit wicket          1
2     Fuller       Catch          4
3      Short       Catch          3
4     length      Bowled          1
5     length       Catch          5
6     length  Hit wicket          1
7       nill     Not out          1

In [30]:
out_df["bowl_speed"].describe()

count      17
unique     14
top       136
freq        3
Name: bowl_speed, dtype: object

In [31]:
out_df.groupby("bowl_speed").size().reset_index(name="out")

   bowl_speed  out
0         131    1
1         133    1
2         134    1
3         135    1
4         136    3
5         137    2
6         138    1
7         143    1
8          87    1
9          90    1
10         93    1
11         94    1
12         96    1
13       nill    1

In [32]:
out_df = df[df["dismissed"] != "Not out"]

In [33]:
out_df.groupby(["bowling_type", "length","bowl_speed","match_over","bowler_over"]).size().reset_index(name="out")

             bowling_type     length bowl_speed match_over bowler_over  out
0    Left arm fast medium     Fuller        131       4th            1    1
1          Right arm fast     Fuller        136        1st           1    1
2          Right arm fast      Short        143       16th           3    1
3   Right arm fast medium  Full toss        136       13th           3    1
4   Right arm fast medium  Full toss        137       17th           3    1
5   Right arm fast medium      Short        134       15th           4    1
6   Right arm fast medium     length        135        3rd           2    1
7     Right arm leg break     length         93       11th           1    1
8     Right arm leg break     length         96        6th           1    1
9      Right arm leg spin     Fuller         94       11th           3    1
10  Right arm medium fast     Fuller        133       19th           4    1
11  Right arm medium fast      Short        138       4th            2    1
12  Right arm medium fast     length        136        3rd           2    1
13  Right arm medium fast     length        137        3rd           1    1
14     Right arm off spin     length         90        6th           1    1
15      left arm off spin     length         87       17th           4    1

In [34]:
Q1=df["runs"].quantile(0.25)
Q3=df["runs"].quantile(0.75)
IQR=Q3-Q1

In [35]:
df.corr(numeric_only=True)

,runs,ball_played,strikerate,4s,6s,Boundary Runs,Singles,Boundary %,Fifty,Century
runs,1.000000,0.982281,0.637936,0.867801,0.854769,0.969783,0.904789,0.163228,0.919809,0.456745
ball_played,0.982281,1.000000,0.577659,0.853085,0.784499,0.922288,0.941667,0.127122,0.914868,0.431182
strikerate,0.637936,0.577659,1.000000,0.619516,0.559350,0.664005,0.498043,0.721612,0.586006,0.180816
4s,0.867801,0.853085,0.619516,1.000000,0.577729,0.890798,0.699261,0.297623,0.833473,0.547025
6s,0.854769,0.784499,0.559350,0.577729,1.000000,0.885534,0.674597,0.184045,0.699127,0.419455
Boundary Runs,0.969783,0.922288,0.664005,0.890798,0.885534,1.000000,0.773553,0.271858,0.863599,0.544865
Singles,0.904789,0.941667,0.498043,0.699261,0.674597,0.773553,1.000000,-0.050543,0.881835,0.235348
Boundary %,0.163228,0.127122,0.721612,0.297623,0.184045,0.271858,-0.050543,1.000000,0.045211,0.142099
Fifty,0.919809,0.914868,0.586006,0.833473,0.699127,0.863599,0.881835,0.045211,1.000000,0.235702
Century,0.456745,0.431182,0.180816,0.547025,0.419455,0.544865,0.235348,0.142099,0.235702,1.000000

In [36]:
df.to_csv("cleaned_data.csv",index=False)

In [37]:
from sqlalchemy import create_engine
username = "postgres"
password = "0360"
host = "localhost"
port ="2002"
database = "sai2026"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="cricket"
df.to_sql(table_name, engine, if_exists ="replace", index= False)
print(f"Data successfully loaded into table'{table_name}'in database '{database}',")

Data successfully loaded into table'cricket'in database 'sai2026',